# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle
# see also: https://github.com/AppliedEnergistics/Applied-Energistics-2/tree/master/.github/workflows

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
        cache: 'gradle'
    - name: Setup and Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build --stacktrace --no-daemon    
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: build/libs/
#    - name: Validate no assets
#      run: test ! -d ./src/generated
#    - name: Generate assets
#      run: ./gradlew runData
#    - name: Validate assets
#      run: test -d ./src/generated/resources/.cache

#    - name: Run Game Tests
#      run: ./gradlew runGametest
